- hosts: openstack
  gather_facts: true

  vars:
    kolla_serve_dir: /srv/kolla
    kolla_config_dir: /etc/kolla
    kolla_venv_dir: "{{ kolla_serve_dir }}/venv"
    kolla_deploy_logs_dir: "/var/log/kolla-deploy"

    kolla_venv_cmd: ". {{ kolla_serve_dir }}/venv/bin/activate"

  tasks:
    - block:
      - name: Ensure system is up-to date
        ansible.builtin.apt:
          update_cache: true
          upgrade: dist

      - name: Check if reboot required
        ansible.builtin.stat:
          path: /var/run/reboot-required
        register: reboot_required_file

      - name: Reboot if required
        ansible.builtin.reboot:
        when: reboot_required_file.stat.exists == true
      become: true
      tags: system_upgrade

    # Network setup

    - block:
      - name: Ensure that systemd network veth interface as external NIC exists
        ansible.builtin.copy:
          src: 25-veth-openstack.netdev
          dest: /lib/systemd/network/25-veth-openstack.netdev
          owner: root
          group: root
          mode: '0644'
        register: systemd_veth

      - name: Restart systemd-networkd if required
        ansible.builtin.systemd_service:
          name: systemd-networkd
          state: restarted
        when: systemd_veth is changed

      - name: Ensure that netplan config exists
        ansible.builtin.copy:
          src: 50-cloud-init.yaml
          dest: /etc/netplan/50-cloud-init.yaml
          owner: root
          group: root
          mode: '0600'
        register: netplan_config

      - name: Reapply netplan config if required
        ansible.builtin.command: netplan generate && netplan apply
        when: netplan_config is changed
      become: true
      tags: network

    # Kolla preparations

    - block:
      - name: Ensure that kolla serve directory exists
        become: true
        ansible.builtin.file:
          path: "{{ kolla_serve_dir }}"
          state: directory
          owner: ubuntu
          group: ubuntu
          mode: '0755'

      - name: Ensure that kolla config directory exists
        become: true
        ansible.builtin.file:
          path: "{{ kolla_config_dir }}"
          state: directory
          owner: ubuntu
          group: ubuntu
          mode: '0755'

      - name: Ensure that kolla deploy logs directory exists
        become: true
        ansible.builtin.file:
          path: "{{ kolla_deploy_logs_dir }}"
          state: directory
          owner: ubuntu
          group: ubuntu
          mode: '0755'

      - name: Ensure that apt dependencies are installed
        become: true
        ansible.builtin.apt:
          name:
            - python3-dev
            - python3-venv
            - libffi-dev
            - gcc
            - libssl-dev

      - name: Ensure that kolla python venv exists
        ansible.builtin.pip:
          name:
            - pip
          state: latest
          virtualenv: "{{ kolla_venv_dir }}"
          virtualenv_command: python3 -m venv

      - name: Ensure that kolla-ansible is installed
        ansible.builtin.pip:
          name:
            - ansible-core>=2.14,<2.16
            - git+https://opendev.org/openstack/kolla-ansible@stable/2023.2
          virtualenv: "{{ kolla_venv_dir }}"

      - name: Ensure that kolla-ansible dependencies are installed
        ansible.builtin.shell: "{{ kolla_venv_cmd }} && kolla-ansible install-deps >{{ kolla_deploy_logs_dir }}/install-deps.log 2>{{ kolla_deploy_logs_dir }}/install-deps-error.log"
      tags: kolla-preparations
